version: '3.7'

services:
  app:
    container_name: gopg
    build: .
    ports:
     - 80:${APP_PORT:-8080}
    volumes:
      - ./:/go/src
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "'echo -e \"GET / HTTP/1.0\nHost: localhost\n\n\" | nc localhost ${APP_PORT}'"]
      interval: 10s
      timeout: 3s
      retries: 10